<a href="https://colab.research.google.com/github/Aditya97p/datatrained_practice_problem/blob/main/Day2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import requests
import csv
import pandas as pd
import numpy as np

In [2]:
url = "https://github.com/training-ml/Files/raw/main/raw_data.csv"

df = pd.read_csv(url)

In [3]:
df.head()

,id,Employee Full Name,DOB,email,gender,Company,Country,Income.1,Income.2
0,201.0,Salim Pound,02-12-2018,spound0@spotify.com,Male,Google,India,$46476.6380809961,529.0
1,202.0,Madelene Lutas,9/20/2018,mlutas1@si.edu,Female,Amazon,USA,$54174.6879482406,720.0
2,203.0,Dolli Swanbourne,11/18/2018,dswanbourne2@istockphoto.com,Female,Intel,UAS,NaN,234.0
3,204.0,Graeme Croisier,9/29/2018,NaN,Male,Accenture,Canada,$46784.6308786279,657.0
4,205.0,Jillana Physic,4/19/2018,jphysic4@yellowbook.com,Female,Accenture,NaN,$57486.4955595568,1947.0

In [4]:
new_data = {
    'id': 210,
    'Employee Full Name': 'Jim Carry',
    'DOB': '1/1/1970',
    'email': 'jim.carry@gmail.com',
    'gender': 'Male',
    'Company': 'Amazon',
    'Country': 'USA',
    'Income.1': 12349.556,
    'Income.2': 2365
}

# Use the loc method to insert the new row at index 9
df.loc[9] = new_data

# Print the DataFrame to verify the addition
print(df)

       id   Employee Full Name         DOB                          email  \
0   201.0          Salim Pound  02-12-2018            spound0@spotify.com
1   202.0       Madelene Lutas   9/20/2018                 mlutas1@si.edu
2   203.0     Dolli Swanbourne  11/18/2018   dswanbourne2@istockphoto.com
3   204.0      Graeme Croisier   9/29/2018                            NaN
4   205.0       Jillana Physic   4/19/2018        jphysic4@yellowbook.com
5   206.0      Anetta Yokelman   4/26/2018        ayokelman5@berkeley.edu
6   207.0    Modesta Batterson   3/28/2018                            NaN
7   208.0          Melina Boon  12/18/2017               mboon7@weibo.com
8   209.0            Nomi Warn   1/16/2018               nwarn8@sogou.com
9   210.0            Jim Carry    1/1/1970            jim.carry@gmail.com
10  211.0       Charleen Auden   4/15/2018                caudena@nba.com
11  212.0          Dame Povele   6/26/2018         dpoveleb@bloglovin.com
12  213.0    Jesse Engelbrecht   4/16/2018        jengelbrechtc@google.ru
13  214.0       Camey Barensen   8/21/2018           cbarensend@globo.com
14  215.0     Alexandro Sember  04-08-2018               asembere@ibm.com
15  216.0         Myrtia Towne   2/14/2018              mtownef@ifeng.com
16  217.0       Shay Cakebread   9/27/2018           scakebreadg@webs.com
17  218.0      Nerta McCutheon  01-07-2018               nmccutheonh@t.co
18  219.0       Patin Mitchely   5/21/2018         pmitchelyi@tinypic.com
19  220.0  Malinda Heistermann  10/30/2018  mheistermannj@list-manage.com

    gender    Company Country           Income.1  Income.2
0     Male     Google   India  $46476.6380809961     529.0
1   Female     Amazon     USA  $54174.6879482406     720.0
2   Female      Intel     UAS                NaN     234.0
3     Male  Accenture  Canada  $46784.6308786279     657.0
4   Female  Accenture     NaN  $57486.4955595568    1947.0
5   Female      Intel   India                  $     952.0
6   Female      Intel   India                NaN      32.0
7     Male     Amazon   India                NaN    1901.0
8   Female     Amazon     UAS  $28602.4353770562       NaN
9     Male     Amazon     USA          12349.556    2365.0
10  Female  Accenture     USA  $47119.1747795038     920.0
11    Male     Amazon     NaN                NaN    1286.0
12  Female     Amazon  Canada  $55804.9256874294       NaN
13    Male     Google  Canada  $44191.4731284524      46.0
14    Male     Google  Russia                  $     568.0
15  Female     Google   India  $44481.7651905881    1553.0
16    Male     Google   India  $55719.9621570482    1013.0
17  Female     Amazon   India  $33767.5099948119    1920.0
18    Male     Amazon  Russia  $7101.35196996979    1952.0
19  Female      Intel  Russia  $43363.0787072359    1668.0

In [5]:
new_emails = ['graeme.Croisier@gmail.com']
new_emails1 = ['Modesta.Batterson@gmail.com']


positions_to_add_emails = [3]

for i, position in enumerate(positions_to_add_emails):
    if pd.isna(df.loc[position, 'email']):
        df.loc[position, 'email'] = new_emails[i]

positions_to_add_emails = [6]
for i, position in enumerate(positions_to_add_emails):
    if pd.isna(df.loc[position, 'email']):
        df.loc[position, 'email'] = new_emails1[i]

# Print the updated DataFrame
print(df)

       id   Employee Full Name         DOB                          email  \
0   201.0          Salim Pound  02-12-2018            spound0@spotify.com
1   202.0       Madelene Lutas   9/20/2018                 mlutas1@si.edu
2   203.0     Dolli Swanbourne  11/18/2018   dswanbourne2@istockphoto.com
3   204.0      Graeme Croisier   9/29/2018      graeme.Croisier@gmail.com
4   205.0       Jillana Physic   4/19/2018        jphysic4@yellowbook.com
5   206.0      Anetta Yokelman   4/26/2018        ayokelman5@berkeley.edu
6   207.0    Modesta Batterson   3/28/2018    Modesta.Batterson@gmail.com
7   208.0          Melina Boon  12/18/2017               mboon7@weibo.com
8   209.0            Nomi Warn   1/16/2018               nwarn8@sogou.com
9   210.0            Jim Carry    1/1/1970            jim.carry@gmail.com
10  211.0       Charleen Auden   4/15/2018                caudena@nba.com
11  212.0          Dame Povele   6/26/2018         dpoveleb@bloglovin.com
12  213.0    Jesse Engelbrecht   4/16/2018        jengelbrechtc@google.ru
13  214.0       Camey Barensen   8/21/2018           cbarensend@globo.com
14  215.0     Alexandro Sember  04-08-2018               asembere@ibm.com
15  216.0         Myrtia Towne   2/14/2018              mtownef@ifeng.com
16  217.0       Shay Cakebread   9/27/2018           scakebreadg@webs.com
17  218.0      Nerta McCutheon  01-07-2018               nmccutheonh@t.co
18  219.0       Patin Mitchely   5/21/2018         pmitchelyi@tinypic.com
19  220.0  Malinda Heistermann  10/30/2018  mheistermannj@list-manage.com

    gender    Company Country           Income.1  Income.2
0     Male     Google   India  $46476.6380809961     529.0
1   Female     Amazon     USA  $54174.6879482406     720.0
2   Female      Intel     UAS                NaN     234.0
3     Male  Accenture  Canada  $46784.6308786279     657.0
4   Female  Accenture     NaN  $57486.4955595568    1947.0
5   Female      Intel   India                  $     952.0
6   Female      Intel   India                NaN      32.0
7     Male     Amazon   India                NaN    1901.0
8   Female     Amazon     UAS  $28602.4353770562       NaN
9     Male     Amazon     USA          12349.556    2365.0
10  Female  Accenture     USA  $47119.1747795038     920.0
11    Male     Amazon     NaN                NaN    1286.0
12  Female     Amazon  Canada  $55804.9256874294       NaN
13    Male     Google  Canada  $44191.4731284524      46.0
14    Male     Google  Russia                  $     568.0
15  Female     Google   India  $44481.7651905881    1553.0
16    Male     Google   India  $55719.9621570482    1013.0
17  Female     Amazon   India  $33767.5099948119    1920.0
18    Male     Amazon  Russia  $7101.35196996979    1952.0
19  Female      Intel  Russia  $43363.0787072359    1668.0

In [6]:
df['Country'].unique()

array(['India', 'USA', 'UAS', 'Canada', nan, 'Russia'], dtype=object)

In [7]:
df['Country']= df['Country'].replace('UAS','USA')

In [8]:
print(df)

       id   Employee Full Name         DOB                          email  \
0   201.0          Salim Pound  02-12-2018            spound0@spotify.com
1   202.0       Madelene Lutas   9/20/2018                 mlutas1@si.edu
2   203.0     Dolli Swanbourne  11/18/2018   dswanbourne2@istockphoto.com
3   204.0      Graeme Croisier   9/29/2018      graeme.Croisier@gmail.com
4   205.0       Jillana Physic   4/19/2018        jphysic4@yellowbook.com
5   206.0      Anetta Yokelman   4/26/2018        ayokelman5@berkeley.edu
6   207.0    Modesta Batterson   3/28/2018    Modesta.Batterson@gmail.com
7   208.0          Melina Boon  12/18/2017               mboon7@weibo.com
8   209.0            Nomi Warn   1/16/2018               nwarn8@sogou.com
9   210.0            Jim Carry    1/1/1970            jim.carry@gmail.com
10  211.0       Charleen Auden   4/15/2018                caudena@nba.com
11  212.0          Dame Povele   6/26/2018         dpoveleb@bloglovin.com
12  213.0    Jesse Engelbrecht   4/16/2018        jengelbrechtc@google.ru
13  214.0       Camey Barensen   8/21/2018           cbarensend@globo.com
14  215.0     Alexandro Sember  04-08-2018               asembere@ibm.com
15  216.0         Myrtia Towne   2/14/2018              mtownef@ifeng.com
16  217.0       Shay Cakebread   9/27/2018           scakebreadg@webs.com
17  218.0      Nerta McCutheon  01-07-2018               nmccutheonh@t.co
18  219.0       Patin Mitchely   5/21/2018         pmitchelyi@tinypic.com
19  220.0  Malinda Heistermann  10/30/2018  mheistermannj@list-manage.com

    gender    Company Country           Income.1  Income.2
0     Male     Google   India  $46476.6380809961     529.0
1   Female     Amazon     USA  $54174.6879482406     720.0
2   Female      Intel     USA                NaN     234.0
3     Male  Accenture  Canada  $46784.6308786279     657.0
4   Female  Accenture     NaN  $57486.4955595568    1947.0
5   Female      Intel   India                  $     952.0
6   Female      Intel   India                NaN      32.0
7     Male     Amazon   India                NaN    1901.0
8   Female     Amazon     USA  $28602.4353770562       NaN
9     Male     Amazon     USA          12349.556    2365.0
10  Female  Accenture     USA  $47119.1747795038     920.0
11    Male     Amazon     NaN                NaN    1286.0
12  Female     Amazon  Canada  $55804.9256874294       NaN
13    Male     Google  Canada  $44191.4731284524      46.0
14    Male     Google  Russia                  $     568.0
15  Female     Google   India  $44481.7651905881    1553.0
16    Male     Google   India  $55719.9621570482    1013.0
17  Female     Amazon   India  $33767.5099948119    1920.0
18    Male     Amazon  Russia  $7101.35196996979    1952.0
19  Female      Intel  Russia  $43363.0787072359    1668.0

In [9]:
df.dtypes

id                    float64
Employee Full Name     object
DOB                    object
email                  object
gender                 object
Company                object
Country                object
Income.1               object
Income.2              float64
dtype: object

need to convert datatype to numeric for that column should not have null values so adding median values in null values

In [10]:
df['Income.1']=df['Income.1'].str.replace("$","")
df

<ipython-input-10-4bfb1a91e674>:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['Income.1']=df['Income.1'].str.replace("$","")

,id,Employee Full Name,DOB,email,gender,Company,Country,Income.1,Income.2
0,201.0,Salim Pound,02-12-2018,spound0@spotify.com,Male,Google,India,46476.6380809961,529.0
1,202.0,Madelene Lutas,9/20/2018,mlutas1@si.edu,Female,Amazon,USA,54174.6879482406,720.0
2,203.0,Dolli Swanbourne,11/18/2018,dswanbourne2@istockphoto.com,Female,Intel,USA,NaN,234.0
3,204.0,Graeme Croisier,9/29/2018,graeme.Croisier@gmail.com,Male,Accenture,Canada,46784.6308786279,657.0
4,205.0,Jillana Physic,4/19/2018,jphysic4@yellowbook.com,Female,Accenture,NaN,57486.4955595568,1947.0
5,206.0,Anetta Yokelman,4/26/2018,ayokelman5@berkeley.edu,Female,Intel,India,,952.0
6,207.0,Modesta Batterson,3/28/2018,Modesta.Batterson@gmail.com,Female,Intel,India,NaN,32.0
7,208.0,Melina Boon,12/18/2017,mboon7@weibo.com,Male,Amazon,India,NaN,1901.0
8,209.0,Nomi Warn,1/16/2018,nwarn8@sogou.com,Female,Amazon,USA,28602.4353770562,NaN
9,210.0,Jim Carry,1/1/1970,jim.carry@gmail.com,Male,Amazon,USA,NaN,2365.0
10,211.0,Charleen Auden,4/15/2018,caudena@nba.com,Female,Accenture,USA,47119.1747795038,920.0
11,212.0,Dame Povele,6/26/2018,dpoveleb@bloglovin.com,Male,Amazon,NaN,NaN,1286.0
12,213.0,Jesse Engelbrecht,4/16/2018,jengelbrechtc@google.ru,Female,Amazon,Canada,55804.9256874294,NaN
13,214.0,Camey Barensen,8/21/2018,cbarensend@globo.com,Male,Google,Canada,44191.4731284524,46.0
14,215.0,Alexandro Sember,04-08-2018,asembere@ibm.com,Male,Google,Russia,,568.0
15,216.0,Myrtia Towne,2/14/2018,mtownef@ifeng.com,Female,Google,India,44481.7651905881,1553.0
16,217.0,Shay Cakebread,9/27/2018,scakebreadg@webs.com,Male,Google,India,55719.9621570482,1013.0
17,218.0,Nerta McCutheon,01-07-2018,nmccutheonh@t.co,Female,Amazon,India,33767.5099948119,1920.0
18,219.0,Patin Mitchely,5/21/2018,pmitchelyi@tinypic.com,Male,Amazon,Russia,7101.35196996979,1952.0
19,220.0,Malinda Heistermann,10/30/2018,mheistermannj@list-manage.com,Female,Intel,Russia,43363.0787072359,1668.0

In [11]:
df['Income.1']=df['Income.1'].replace("",np.nan)
df

,id,Employee Full Name,DOB,email,gender,Company,Country,Income.1,Income.2
0,201.0,Salim Pound,02-12-2018,spound0@spotify.com,Male,Google,India,46476.6380809961,529.0
1,202.0,Madelene Lutas,9/20/2018,mlutas1@si.edu,Female,Amazon,USA,54174.6879482406,720.0
2,203.0,Dolli Swanbourne,11/18/2018,dswanbourne2@istockphoto.com,Female,Intel,USA,NaN,234.0
3,204.0,Graeme Croisier,9/29/2018,graeme.Croisier@gmail.com,Male,Accenture,Canada,46784.6308786279,657.0
4,205.0,Jillana Physic,4/19/2018,jphysic4@yellowbook.com,Female,Accenture,NaN,57486.4955595568,1947.0
5,206.0,Anetta Yokelman,4/26/2018,ayokelman5@berkeley.edu,Female,Intel,India,NaN,952.0
6,207.0,Modesta Batterson,3/28/2018,Modesta.Batterson@gmail.com,Female,Intel,India,NaN,32.0
7,208.0,Melina Boon,12/18/2017,mboon7@weibo.com,Male,Amazon,India,NaN,1901.0
8,209.0,Nomi Warn,1/16/2018,nwarn8@sogou.com,Female,Amazon,USA,28602.4353770562,NaN
9,210.0,Jim Carry,1/1/1970,jim.carry@gmail.com,Male,Amazon,USA,NaN,2365.0
10,211.0,Charleen Auden,4/15/2018,caudena@nba.com,Female,Accenture,USA,47119.1747795038,920.0
11,212.0,Dame Povele,6/26/2018,dpoveleb@bloglovin.com,Male,Amazon,NaN,NaN,1286.0
12,213.0,Jesse Engelbrecht,4/16/2018,jengelbrechtc@google.ru,Female,Amazon,Canada,55804.9256874294,NaN
13,214.0,Camey Barensen,8/21/2018,cbarensend@globo.com,Male,Google,Canada,44191.4731284524,46.0
14,215.0,Alexandro Sember,04-08-2018,asembere@ibm.com,Male,Google,Russia,NaN,568.0
15,216.0,Myrtia Towne,2/14/2018,mtownef@ifeng.com,Female,Google,India,44481.7651905881,1553.0
16,217.0,Shay Cakebread,9/27/2018,scakebreadg@webs.com,Male,Google,India,55719.9621570482,1013.0
17,218.0,Nerta McCutheon,01-07-2018,nmccutheonh@t.co,Female,Amazon,India,33767.5099948119,1920.0
18,219.0,Patin Mitchely,5/21/2018,pmitchelyi@tinypic.com,Male,Amazon,Russia,7101.35196996979,1952.0
19,220.0,Malinda Heistermann,10/30/2018,mheistermannj@list-manage.com,Female,Intel,Russia,43363.0787072359,1668.0

In [12]:
df['Income.1']=df['Income.1'].astype(float)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  20 non-null     float64
 1   Employee Full Name  20 non-null     object
 2   DOB                 20 non-null     object
 3   email               20 non-null     object
 4   gender              20 non-null     object
 5   Company             20 non-null     object
 6   Country             18 non-null     object
 7   Income.1            13 non-null     float64
 8   Income.2            18 non-null     float64
dtypes: float64(3), object(6)
memory usage: 1.5+ KB

In [13]:
df

,id,Employee Full Name,DOB,email,gender,Company,Country,Income.1,Income.2
0,201.0,Salim Pound,02-12-2018,spound0@spotify.com,Male,Google,India,46476.638081,529.0
1,202.0,Madelene Lutas,9/20/2018,mlutas1@si.edu,Female,Amazon,USA,54174.687948,720.0
2,203.0,Dolli Swanbourne,11/18/2018,dswanbourne2@istockphoto.com,Female,Intel,USA,NaN,234.0
3,204.0,Graeme Croisier,9/29/2018,graeme.Croisier@gmail.com,Male,Accenture,Canada,46784.630879,657.0
4,205.0,Jillana Physic,4/19/2018,jphysic4@yellowbook.com,Female,Accenture,NaN,57486.495560,1947.0
5,206.0,Anetta Yokelman,4/26/2018,ayokelman5@berkeley.edu,Female,Intel,India,NaN,952.0
6,207.0,Modesta Batterson,3/28/2018,Modesta.Batterson@gmail.com,Female,Intel,India,NaN,32.0
7,208.0,Melina Boon,12/18/2017,mboon7@weibo.com,Male,Amazon,India,NaN,1901.0
8,209.0,Nomi Warn,1/16/2018,nwarn8@sogou.com,Female,Amazon,USA,28602.435377,NaN
9,210.0,Jim Carry,1/1/1970,jim.carry@gmail.com,Male,Amazon,USA,NaN,2365.0
10,211.0,Charleen Auden,4/15/2018,caudena@nba.com,Female,Accenture,USA,47119.174780,920.0
11,212.0,Dame Povele,6/26/2018,dpoveleb@bloglovin.com,Male,Amazon,NaN,NaN,1286.0
12,213.0,Jesse Engelbrecht,4/16/2018,jengelbrechtc@google.ru,Female,Amazon,Canada,55804.925687,NaN
13,214.0,Camey Barensen,8/21/2018,cbarensend@globo.com,Male,Google,Canada,44191.473128,46.0
14,215.0,Alexandro Sember,04-08-2018,asembere@ibm.com,Male,Google,Russia,NaN,568.0
15,216.0,Myrtia Towne,2/14/2018,mtownef@ifeng.com,Female,Google,India,44481.765191,1553.0
16,217.0,Shay Cakebread,9/27/2018,scakebreadg@webs.com,Male,Google,India,55719.962157,1013.0
17,218.0,Nerta McCutheon,01-07-2018,nmccutheonh@t.co,Female,Amazon,India,33767.509995,1920.0
18,219.0,Patin Mitchely,5/21/2018,pmitchelyi@tinypic.com,Male,Amazon,Russia,7101.351970,1952.0
19,220.0,Malinda Heistermann,10/30/2018,mheistermannj@list-manage.com,Female,Intel,Russia,43363.078707,1668.0

In [15]:
df['Income.1'].fillna(df['Income.1'].mean(),inplace=True)

In [16]:
df['Income.2'].fillna(df['Income.2'].mean(),inplace=True)

In [17]:
df['Total_Income']=df['Income.1']+df['Income.2']

In [18]:
df

,id,Employee Full Name,DOB,email,gender,Company,Country,Income.1,Income.2,Total_Income
0,201.0,Salim Pound,02-12-2018,spound0@spotify.com,Male,Google,India,46476.638081,529.000000,47005.638081
1,202.0,Madelene Lutas,9/20/2018,mlutas1@si.edu,Female,Amazon,USA,54174.687948,720.000000,54894.687948
2,203.0,Dolli Swanbourne,11/18/2018,dswanbourne2@istockphoto.com,Female,Intel,USA,43467.240728,234.000000,43701.240728
3,204.0,Graeme Croisier,9/29/2018,graeme.Croisier@gmail.com,Male,Accenture,Canada,46784.630879,657.000000,47441.630879
4,205.0,Jillana Physic,4/19/2018,jphysic4@yellowbook.com,Female,Accenture,NaN,57486.495560,1947.000000,59433.495560
5,206.0,Anetta Yokelman,4/26/2018,ayokelman5@berkeley.edu,Female,Intel,India,43467.240728,952.000000,44419.240728
6,207.0,Modesta Batterson,3/28/2018,Modesta.Batterson@gmail.com,Female,Intel,India,43467.240728,32.000000,43499.240728
7,208.0,Melina Boon,12/18/2017,mboon7@weibo.com,Male,Amazon,India,43467.240728,1901.000000,45368.240728
8,209.0,Nomi Warn,1/16/2018,nwarn8@sogou.com,Female,Amazon,USA,28602.435377,1125.722222,29728.157599
9,210.0,Jim Carry,1/1/1970,jim.carry@gmail.com,Male,Amazon,USA,43467.240728,2365.000000,45832.240728
10,211.0,Charleen Auden,4/15/2018,caudena@nba.com,Female,Accenture,USA,47119.174780,920.000000,48039.174780
11,212.0,Dame Povele,6/26/2018,dpoveleb@bloglovin.com,Male,Amazon,NaN,43467.240728,1286.000000,44753.240728
12,213.0,Jesse Engelbrecht,4/16/2018,jengelbrechtc@google.ru,Female,Amazon,Canada,55804.925687,1125.722222,56930.647910
13,214.0,Camey Barensen,8/21/2018,cbarensend@globo.com,Male,Google,Canada,44191.473128,46.000000,44237.473128
14,215.0,Alexandro Sember,04-08-2018,asembere@ibm.com,Male,Google,Russia,43467.240728,568.000000,44035.240728
15,216.0,Myrtia Towne,2/14/2018,mtownef@ifeng.com,Female,Google,India,44481.765191,1553.000000,46034.765191
16,217.0,Shay Cakebread,9/27/2018,scakebreadg@webs.com,Male,Google,India,55719.962157,1013.000000,56732.962157
17,218.0,Nerta McCutheon,01-07-2018,nmccutheonh@t.co,Female,Amazon,India,33767.509995,1920.000000,35687.509995
18,219.0,Patin Mitchely,5/21/2018,pmitchelyi@tinypic.com,Male,Amazon,Russia,7101.351970,1952.000000,9053.351970
19,220.0,Malinda Heistermann,10/30/2018,mheistermannj@list-manage.com,Female,Intel,Russia,43363.078707,1668.000000,45031.078707